/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ASK_QUESTION_MEMBERS: typeof import('./lib/xmtpGroups').ASK_QUESTION_MEMBERS
  const EffectScope: typeof import('vue').EffectScope
  const METRO_API_URL: typeof import('./lib/xmtpGroups').METRO_API_URL
  const XMTP_USER_PREFIX: typeof import('./lib/xmtp').XMTP_USER_PREFIX
  const acceptRequestConv: typeof import('./lib/xmtpRequests').acceptRequestConv
  const addGroupMembers: typeof import('./lib/xmtpGroups').addGroupMembers
  const applyConsentToRows: typeof import('./lib/channelsCache').applyConsentToRows
  const blockRequestConv: typeof import('./lib/xmtpRequests').blockRequestConv
  const cachedRows: typeof import('./lib/channelsCache').cachedRows
  const computeMemberRoles: typeof import('./lib/useGroupDetailHelpers').computeMemberRoles
  const computed: typeof import('vue').computed
  const convIdOfLine: typeof import('./lib/xmtp').convIdOfLine
  const convOfLine: typeof import('./lib/xmtp').convOfLine
  const createApp: typeof import('vue').createApp
  const createAskQuestionGroup: typeof import('./lib/xmtpGroups').createAskQuestionGroup
  const createGroup: typeof import('./lib/xmtpGroups').createGroup
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const envelopeOfXmtpMessage: typeof import('./lib/xmtpFeed').envelopeOfXmtpMessage
  const getCachedXmtpClient: typeof import('./lib/xmtp').getCachedXmtpClient
  const getConvConsent: typeof import('./lib/xmtpConsent').getConvConsent
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getHostAccount: typeof import('./lib/hostSigner').getHostAccount
  const getLastReadNs: typeof import('./lib/xmtpConsent').getLastReadNs
  const getOrCreateXmtpClient: typeof import('./lib/xmtp').getOrCreateXmtpClient
  const getXmtpAccountInfo: typeof import('./lib/xmtp').getXmtpAccountInfo
  const getXmtpEnv: typeof import('./lib/xmtp').getXmtpEnv
  const groupMemberEthAddresses: typeof import('./lib/xmtpResolve').groupMemberEthAddresses
  const h: typeof import('vue').h
  const hostSigner: typeof import('./lib/hostSigner').hostSigner
  const hydrateCachedRows: typeof import('./lib/channelsCache').hydrateCachedRows
  const inject: typeof import('vue').inject
  const installEmbedThemeBridge: typeof import('./lib/embedBridge').installEmbedThemeBridge
  const installThemeClassEffect: typeof import('./lib/theme').installThemeClassEffect
  const isAddressLike: typeof import('./lib/stamp').isAddressLike
  const isArchived: typeof import('./lib/archived').isArchived
  const isDomainLike: typeof import('./lib/stamp').isDomainLike
  const isProxy: typeof import('vue').isProxy
  const isReactionEntry: typeof import('./lib/xmtpFeed').isReactionEntry
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const lineOfConv: typeof import('./lib/xmtp').lineOfConv
  const lineOfDmPeer: typeof import('./lib/xmtp').lineOfDmPeer
  const listRequestConvs: typeof import('./lib/xmtpRequests').listRequestConvs
  const loadArchivedIds: typeof import('./lib/archived').loadArchivedIds
  const loadCachedProfile: typeof import('./lib/profile').loadCachedProfile
  const lookupName: typeof import('./lib/stamp').lookupName
  const mapCoordsOf: typeof import('./lib/embedDetect').mapCoordsOf
  const markConvRead: typeof import('./lib/channelsCache').markConvRead
  const markConvReadSynced: typeof import('./lib/xmtpConsent').markConvReadSynced
  const markConvUnread: typeof import('./lib/channelsCache').markConvUnread
  const markConvUnreadSynced: typeof import('./lib/xmtpConsent').markConvUnreadSynced
  const markRaw: typeof import('vue').markRaw
  const memberInboxToAddressMap: typeof import('./lib/xmtpResolve').memberInboxToAddressMap
  const metroConvIdOf: typeof import('./lib/xmtp').metroConvIdOf
  const metroDmPeerOf: typeof import('./lib/xmtp').metroDmPeerOf
  const mutateMembers: typeof import('./lib/useGroupDetail.mutations').mutateMembers
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onAddMember: typeof import('./lib/useGroupDetail.mutations').onAddMember
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onPickImage: typeof import('./lib/useGroupDetail.mutations').onPickImage
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onSaveDescription: typeof import('./lib/useGroupDetail.mutations').onSaveDescription
  const onSaveName: typeof import('./lib/useGroupDetail.mutations').onSaveName
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const openDmWithAddress: typeof import('./lib/xmtpGroups').openDmWithAddress
  const osmTileUrl: typeof import('./lib/embedDetect').osmTileUrl
  const osmTileXY: typeof import('./lib/embedDetect').osmTileXY
  const ownEmojisByMessage: typeof import('./lib/xmtpFeed').ownEmojisByMessage
  const peerEthAddressOfDm: typeof import('./lib/xmtpResolve').peerEthAddressOfDm
  const postCloseToParent: typeof import('./lib/embedBridge').postCloseToParent
  const postUnreadToParent: typeof import('./lib/embedBridge').postUnreadToParent
  const provide: typeof import('vue').provide
  const reactionsByMessage: typeof import('./lib/xmtpFeed').reactionsByMessage
  const reactive: typeof import('vue').reactive
  const readProfile: typeof import('./lib/profile').readProfile
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeMember: typeof import('./lib/useGroupDetail.mutations').removeMember
  const renderMarkdown: typeof import('./lib/renderMarkdown').renderMarkdown
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveDomain: typeof import('./lib/stamp').resolveDomain
  const resolveMemberNames: typeof import('./lib/useGroupDetailHelpers').resolveMemberNames
  const resolveSearchInputToAddress: typeof import('./lib/stamp').resolveSearchInputToAddress
  const resolveSelfAddress: typeof import('./lib/useGroupDetailHelpers').resolveSelfAddress
  const runGroupDetailEffect: typeof import('./lib/useGroupDetail.mutations').runGroupDetailEffect
  const runningInIframe: typeof import('./lib/embedBridge').runningInIframe
  const setCachedRows: typeof import('./lib/channelsCache').setCachedRows
  const setLastReadNs: typeof import('./lib/xmtpConsent').setLastReadNs
  const setThemePreference: typeof import('./lib/theme').setThemePreference
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shortAddress: typeof import('./lib/xmtp').shortAddress
  const stampAvatarUrl: typeof import('./lib/xmtp').stampAvatarUrl
  const startChannelStream: typeof import('./lib/useChannelStream').startChannelStream
  const streamConvConsent: typeof import('./lib/xmtpConsent').streamConvConsent
  const subscribeArchived: typeof import('./lib/archived').subscribeArchived
  const summarizeConv: typeof import('./lib/channelsSummarize').summarizeConv
  const syncPreferences: typeof import('./lib/xmtpConsent').syncPreferences
  const systemScheme: typeof import('./lib/theme').systemScheme
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toggleArchived: typeof import('./lib/archived').toggleArchived
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const uploadAvatar: typeof import('./lib/profile').uploadAvatar
  const useAttrs: typeof import('vue').useAttrs
  const useBubbleActions: typeof import('./lib/useBubbleActions').useBubbleActions
  const useChannels: typeof import('./lib/useChannels').useChannels
  const useComposerAttach: typeof import('./lib/useComposerAttach').useComposerAttach
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useEffectiveScheme: typeof import('./lib/kitTheme').useEffectiveScheme
  const useGroupDetail: typeof import('./lib/useGroupDetail').useGroupDetail
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSearchResolution: typeof import('./lib/useSearchResolution').useSearchResolution
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemePreference: typeof import('./lib/theme').useThemePreference
  const useXmtpConversation: typeof import('./lib/useXmtpConversation').useXmtpConversation
  const useXmtpFeed: typeof import('./lib/xmtpFeed').useXmtpFeed
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const xmtpReact: typeof import('./lib/xmtpSend').xmtpReact
  const xmtpReply: typeof import('./lib/xmtpSend').xmtpReply
  const xmtpSendAttachment: typeof import('./lib/xmtpSend').xmtpSendAttachment
  const xmtpSendText: typeof import('./lib/xmtpSend').xmtpSendText
  const youtubeIdOf: typeof import('./lib/embedDetect').youtubeIdOf
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { CachedRow } from './lib/channelsCache'
  import('./lib/channelsCache')
  // @ts-ignore
  export type { ChannelRow } from './lib/channelsSummarize'
  import('./lib/channelsSummarize')
  // @ts-ignore
  export type { PickedMember } from './lib/memberPicker'
  import('./lib/memberPicker')
  // @ts-ignore
  export type { SnapshotProfile } from './lib/profile'
  import('./lib/profile')
  // @ts-ignore
  export type { ThemePreference } from './lib/theme'
  import('./lib/theme')
  // @ts-ignore
  export type { HistoryEntry } from './lib/types'
  import('./lib/types')
  // @ts-ignore
  export type { BubbleActionsDeps, BubbleActions } from './lib/useBubbleActions'
  import('./lib/useBubbleActions')
  // @ts-ignore
  export type { ChannelStreamHandles } from './lib/useChannelStream'
  import('./lib/useChannelStream')
  // @ts-ignore
  export type { ChannelsState } from './lib/useChannels'
  import('./lib/useChannels')
  // @ts-ignore
  export type { GroupDetailState } from './lib/useGroupDetail.mutations'
  import('./lib/useGroupDetail.mutations')
  // @ts-ignore
  export type { GroupDetail } from './lib/useGroupDetail'
  import('./lib/useGroupDetail')
  // @ts-ignore
  export type { GroupShape } from './lib/useGroupDetailHelpers'
  import('./lib/useGroupDetailHelpers')
  // @ts-ignore
  export type { SearchResolution } from './lib/useSearchResolution'
  import('./lib/useSearchResolution')
  // @ts-ignore
  export type { XmtpConversation } from './lib/useXmtpConversation'
  import('./lib/useXmtpConversation')
  // @ts-ignore
  export type { XmtpClient, XmtpInstallationView, XmtpAccountInfo, XmtpEnv } from './lib/xmtp'
  import('./lib/xmtp')
  // @ts-ignore
  export type { XmtpFeedStatus, XmtpFeedHandle } from './lib/xmtpFeed'
  import('./lib/xmtpFeed')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ASK_QUESTION_MEMBERS: UnwrapRef<typeof import('./lib/xmtpGroups')['ASK_QUESTION_MEMBERS']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly METRO_API_URL: UnwrapRef<typeof import('./lib/xmtpGroups')['METRO_API_URL']>
    readonly XMTP_USER_PREFIX: UnwrapRef<typeof import('./lib/xmtp')['XMTP_USER_PREFIX']>
    readonly acceptRequestConv: UnwrapRef<typeof import('./lib/xmtpRequests')['acceptRequestConv']>
    readonly addGroupMembers: UnwrapRef<typeof import('./lib/xmtpGroups')['addGroupMembers']>
    readonly applyConsentToRows: UnwrapRef<typeof import('./lib/channelsCache')['applyConsentToRows']>
    readonly blockRequestConv: UnwrapRef<typeof import('./lib/xmtpRequests')['blockRequestConv']>
    readonly cachedRows: UnwrapRef<typeof import('./lib/channelsCache')['cachedRows']>
    readonly computeMemberRoles: UnwrapRef<typeof import('./lib/useGroupDetailHelpers')['computeMemberRoles']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly convIdOfLine: UnwrapRef<typeof import('./lib/xmtp')['convIdOfLine']>
    readonly convOfLine: UnwrapRef<typeof import('./lib/xmtp')['convOfLine']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createAskQuestionGroup: UnwrapRef<typeof import('./lib/xmtpGroups')['createAskQuestionGroup']>
    readonly createGroup: UnwrapRef<typeof import('./lib/xmtpGroups')['createGroup']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly envelopeOfXmtpMessage: UnwrapRef<typeof import('./lib/xmtpFeed')['envelopeOfXmtpMessage']>
    readonly getCachedXmtpClient: UnwrapRef<typeof import('./lib/xmtp')['getCachedXmtpClient']>
    readonly getConvConsent: UnwrapRef<typeof import('./lib/xmtpConsent')['getConvConsent']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getHostAccount: UnwrapRef<typeof import('./lib/hostSigner')['getHostAccount']>
    readonly getLastReadNs: UnwrapRef<typeof import('./lib/xmtpConsent')['getLastReadNs']>
    readonly getOrCreateXmtpClient: UnwrapRef<typeof import('./lib/xmtp')['getOrCreateXmtpClient']>
    readonly getXmtpAccountInfo: UnwrapRef<typeof import('./lib/xmtp')['getXmtpAccountInfo']>
    readonly getXmtpEnv: UnwrapRef<typeof import('./lib/xmtp')['getXmtpEnv']>
    readonly groupMemberEthAddresses: UnwrapRef<typeof import('./lib/xmtpResolve')['groupMemberEthAddresses']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hostSigner: UnwrapRef<typeof import('./lib/hostSigner')['hostSigner']>
    readonly hydrateCachedRows: UnwrapRef<typeof import('./lib/channelsCache')['hydrateCachedRows']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly installEmbedThemeBridge: UnwrapRef<typeof import('./lib/embedBridge')['installEmbedThemeBridge']>
    readonly installThemeClassEffect: UnwrapRef<typeof import('./lib/theme')['installThemeClassEffect']>
    readonly isAddressLike: UnwrapRef<typeof import('./lib/stamp')['isAddressLike']>
    readonly isArchived: UnwrapRef<typeof import('./lib/archived')['isArchived']>
    readonly isDomainLike: UnwrapRef<typeof import('./lib/stamp')['isDomainLike']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactionEntry: UnwrapRef<typeof import('./lib/xmtpFeed')['isReactionEntry']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly lineOfConv: UnwrapRef<typeof import('./lib/xmtp')['lineOfConv']>
    readonly lineOfDmPeer: UnwrapRef<typeof import('./lib/xmtp')['lineOfDmPeer']>
    readonly listRequestConvs: UnwrapRef<typeof import('./lib/xmtpRequests')['listRequestConvs']>
    readonly loadArchivedIds: UnwrapRef<typeof import('./lib/archived')['loadArchivedIds']>
    readonly loadCachedProfile: UnwrapRef<typeof import('./lib/profile')['loadCachedProfile']>
    readonly mapCoordsOf: UnwrapRef<typeof import('./lib/embedDetect')['mapCoordsOf']>
    readonly markConvRead: UnwrapRef<typeof import('./lib/channelsCache')['markConvRead']>
    readonly markConvReadSynced: UnwrapRef<typeof import('./lib/xmtpConsent')['markConvReadSynced']>
    readonly markConvUnread: UnwrapRef<typeof import('./lib/channelsCache')['markConvUnread']>
    readonly markConvUnreadSynced: UnwrapRef<typeof import('./lib/xmtpConsent')['markConvUnreadSynced']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly memberInboxToAddressMap: UnwrapRef<typeof import('./lib/xmtpResolve')['memberInboxToAddressMap']>
    readonly metroConvIdOf: UnwrapRef<typeof import('./lib/xmtp')['metroConvIdOf']>
    readonly metroDmPeerOf: UnwrapRef<typeof import('./lib/xmtp')['metroDmPeerOf']>
    readonly mutateMembers: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['mutateMembers']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onAddMember: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['onAddMember']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onPickImage: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['onPickImage']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onSaveDescription: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['onSaveDescription']>
    readonly onSaveName: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['onSaveName']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly openDmWithAddress: UnwrapRef<typeof import('./lib/xmtpGroups')['openDmWithAddress']>
    readonly osmTileUrl: UnwrapRef<typeof import('./lib/embedDetect')['osmTileUrl']>
    readonly ownEmojisByMessage: UnwrapRef<typeof import('./lib/xmtpFeed')['ownEmojisByMessage']>
    readonly peerEthAddressOfDm: UnwrapRef<typeof import('./lib/xmtpResolve')['peerEthAddressOfDm']>
    readonly postCloseToParent: UnwrapRef<typeof import('./lib/embedBridge')['postCloseToParent']>
    readonly postUnreadToParent: UnwrapRef<typeof import('./lib/embedBridge')['postUnreadToParent']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactionsByMessage: UnwrapRef<typeof import('./lib/xmtpFeed')['reactionsByMessage']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readProfile: UnwrapRef<typeof import('./lib/profile')['readProfile']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly removeMember: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['removeMember']>
    readonly renderMarkdown: UnwrapRef<typeof import('./lib/renderMarkdown')['renderMarkdown']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveDomain: UnwrapRef<typeof import('./lib/stamp')['resolveDomain']>
    readonly resolveMemberNames: UnwrapRef<typeof import('./lib/useGroupDetailHelpers')['resolveMemberNames']>
    readonly resolveSelfAddress: UnwrapRef<typeof import('./lib/useGroupDetailHelpers')['resolveSelfAddress']>
    readonly runGroupDetailEffect: UnwrapRef<typeof import('./lib/useGroupDetail.mutations')['runGroupDetailEffect']>
    readonly runningInIframe: UnwrapRef<typeof import('./lib/embedBridge')['runningInIframe']>
    readonly setCachedRows: UnwrapRef<typeof import('./lib/channelsCache')['setCachedRows']>
    readonly setLastReadNs: UnwrapRef<typeof import('./lib/xmtpConsent')['setLastReadNs']>
    readonly setThemePreference: UnwrapRef<typeof import('./lib/theme')['setThemePreference']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly shortAddress: UnwrapRef<typeof import('./lib/xmtp')['shortAddress']>
    readonly stampAvatarUrl: UnwrapRef<typeof import('./lib/xmtp')['stampAvatarUrl']>
    readonly startChannelStream: UnwrapRef<typeof import('./lib/useChannelStream')['startChannelStream']>
    readonly streamConvConsent: UnwrapRef<typeof import('./lib/xmtpConsent')['streamConvConsent']>
    readonly subscribeArchived: UnwrapRef<typeof import('./lib/archived')['subscribeArchived']>
    readonly summarizeConv: UnwrapRef<typeof import('./lib/channelsSummarize')['summarizeConv']>
    readonly syncPreferences: UnwrapRef<typeof import('./lib/xmtpConsent')['syncPreferences']>
    readonly systemScheme: UnwrapRef<typeof import('./lib/theme')['systemScheme']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toggleArchived: UnwrapRef<typeof import('./lib/archived')['toggleArchived']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly uploadAvatar: UnwrapRef<typeof import('./lib/profile')['uploadAvatar']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBubbleActions: UnwrapRef<typeof import('./lib/useBubbleActions')['useBubbleActions']>
    readonly useChannels: UnwrapRef<typeof import('./lib/useChannels')['useChannels']>
    readonly useComposerAttach: UnwrapRef<typeof import('./lib/useComposerAttach')['useComposerAttach']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useEffectiveScheme: UnwrapRef<typeof import('./lib/kitTheme')['useEffectiveScheme']>
    readonly useGroupDetail: UnwrapRef<typeof import('./lib/useGroupDetail')['useGroupDetail']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSearchResolution: UnwrapRef<typeof import('./lib/useSearchResolution')['useSearchResolution']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useThemePreference: UnwrapRef<typeof import('./lib/theme')['useThemePreference']>
    readonly useXmtpConversation: UnwrapRef<typeof import('./lib/useXmtpConversation')['useXmtpConversation']>
    readonly useXmtpFeed: UnwrapRef<typeof import('./lib/xmtpFeed')['useXmtpFeed']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly xmtpReact: UnwrapRef<typeof import('./lib/xmtpSend')['xmtpReact']>
    readonly xmtpReply: UnwrapRef<typeof import('./lib/xmtpSend')['xmtpReply']>
    readonly xmtpSendAttachment: UnwrapRef<typeof import('./lib/xmtpSend')['xmtpSendAttachment']>
    readonly xmtpSendText: UnwrapRef<typeof import('./lib/xmtpSend')['xmtpSendText']>
    readonly youtubeIdOf: UnwrapRef<typeof import('./lib/embedDetect')['youtubeIdOf']>
  }
}