/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleActionSheet: typeof import('./components/BubbleActionSheet.vue')['default']
    Composer: typeof import('./components/Composer.vue')['default']
    HeroIcon: typeof import('./components/HeroIcon.vue')['default']
    MessengerBubble: typeof import('./components/MessengerBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/TabBar.vue')['default']
  }
}
