/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountExportSheet: typeof import('./components/AccountExportSheet.vue')['default']
    AccountImportSheet: typeof import('./components/AccountImportSheet.vue')['default']
    ActivityList: typeof import('./components/ActivityList.vue')['default']
    BackupNudge: typeof import('./components/BackupNudge.vue')['default']
    BubbleActionSheet: typeof import('./components/BubbleActionSheet.vue')['default']
    ChannelRow: typeof import('./components/ChannelRow.vue')['default']
    ChannelsSearchBar: typeof import('./components/ChannelsSearchBar.vue')['default']
    Col: typeof import('@stage-labs/kit/vue/col')['default']
    CommonChannels: typeof import('./components/CommonChannels.vue')['default']
    Composer: typeof import('./components/Composer.vue')['default']
    ConversationHeader: typeof import('./components/ConversationHeader.vue')['default']
    GroupAvatarEditor: typeof import('./components/GroupAvatarEditor.vue')['default']
    HoistedTopnav: typeof import('./components/HoistedTopnav.vue')['default']
    InlineEditableText: typeof import('./components/InlineEditableText.vue')['default']
    LocationEmbed: typeof import('./components/LocationEmbed.vue')['default']
    MediaCard: typeof import('./components/MediaCard.vue')['default']
    MemberAddForm: typeof import('./components/MemberAddForm.vue')['default']
    MemberPicker: typeof import('./components/MemberPicker.vue')['default']
    MemberRow: typeof import('./components/MemberRow.vue')['default']
    MessengerBubble: typeof import('./components/MessengerBubble.vue')['default']
    NftGrid: typeof import('./components/NftGrid.vue')['default']
    PaymentComposeSheet: typeof import('./components/PaymentComposeSheet.vue')['default']
    PollCard: typeof import('./components/PollCard.vue')['default']
    PollComposeSheet: typeof import('./components/PollComposeSheet.vue')['default']
    ProposalsBanner: typeof import('./components/ProposalsBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResolution: typeof import('./components/SearchResolution.vue')['default']
    SignRequestComposeSheet: typeof import('./components/SignRequestComposeSheet.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    TokenRow: typeof import('./components/TokenRow.vue')['default']
    Topnav: typeof import('./components/Topnav.vue')['default']
    TopnavIdentity: typeof import('./components/TopnavIdentity.vue')['default']
    TxRow: typeof import('./components/TxRow.vue')['default']
    VoiceMessage: typeof import('./components/VoiceMessage.vue')['default']
    VoiceRecordBar: typeof import('./components/VoiceRecordBar.vue')['default']
    WalletTabs: typeof import('./components/WalletTabs.vue')['default']
    YouTubeEmbed: typeof import('./components/YouTubeEmbed.vue')['default']
  }
}
