
import { FONT_SIZE } from '@stage-labs/kit/tokens';
import type { WidgetRoot } from '@stage-labs/kit/kit';

const SAMPLE_IMAGE =
  'https://cdn.stamp.fyi/avatar/eth:0x2539f6dd5e4ab2c3a30c2b9a0a8a8a8a8a8a79d5?s=160';

export const EXTENSION_WIDGET: WidgetRoot = {
  type: 'Basic',
  children: [
    { type: 'Title', value: 'Hero', size: '7xl' },
    { type: 'Spacer', minSize: 8 },
    {
      type: 'Row',
      gap: 16,
      align: 'center',
      children: [
        { type: 'Spinner', size: 'sm' },
        { type: 'Spinner', size: 'md' },
        { type: 'Spinner', size: 'lg', color: '#2f6df6' },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Switch',
      name: 'demoSwitch',
      checked: true,
      label: 'Notifications',
      onChangeAction: { type: 'demo_switch', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Tabs',
      name: 'demoTabs',
      value: 'overview',
      onChangeAction: { type: 'demo_tabs', handler: 'client' },
      options: [
        { value: 'overview', label: 'Overview', icon: 'wallet' },
        { value: 'activity', label: 'Activity', icon: 'bell' },
        { value: 'settings', label: 'Settings', icon: 'cog' },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'AvatarStack',
      size: 36,
      max: 4,
      items: [
        { src: SAMPLE_IMAGE },
        { src: SAMPLE_IMAGE },
        { fallback: 'AB' },
        { fallback: 'CD' },
        { fallback: 'EF' },
        { fallback: 'GH' },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    { type: 'QRCode', value: 'https://metro.box', size: 140 },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'TextField',
      name: 'demoField',
      value: 'live text',
      placeholder: 'Type here',
      onChangeAction: { type: 'demo_text', handler: 'client' },
      onSelectionChangeAction: { type: 'demo_selection', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'TextField',
      name: 'demoPlainField',
      value: 'Message',
      placeholder: 'Message',
      variant: 'plain',
      fontSize: FONT_SIZE['3xl'],
      fontWeight: 'medium',
      color: { dark: '#e8e8ea', light: '#1c1c1e' },
      paddingX: 8,
      paddingY: 4,
      maxHeight: 210,
      returnKeyType: 'send',
      autoFocus: true,
      focusNonce: 1,
      onChangeAction: { type: 'demo_plain_text', handler: 'client' },
      onSubmitAction: { type: 'demo_plain_submit', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'TextField',
      name: 'demoComposerField',
      value: 'Message',
      placeholder: 'Message',
      variant: 'plain',
      multiline: true,
      autoGrow: true,
      fontSize: FONT_SIZE['3xl'],
      fontWeight: 'medium',
      color: { dark: '#e8e8ea', light: '#1c1c1e' },
      paddingX: 8,
      paddingTop: 4,
      paddingBottom: 8,
      lineHeight: 23,
      maxHeight: 210,
      autoCapitalize: 'sentences',
      focusNonce: 0,
      blurNonce: 0,
      onChangeAction: { type: 'demo_composer_text', handler: 'client' },
      onSelectionChangeAction: { type: 'demo_composer_selection', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Popover',
      side: 'bottom',
      align: 'end',
      trigger: { type: 'Icon', name: 'dotsHorizontal', size: 'lg' },
      items: [
        { id: 'new', label: 'New group', icon: 'plus' },
        { id: 'archived', label: 'Archived', icon: 'archive' },
        { id: 'profile', label: 'Profile', icon: 'user' },
        { id: 'leave', label: 'Leave group', icon: 'logout', danger: true },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Stack',
      width: '100%',
      height: 28,
      children: [
        {
          type: 'Box',
          position: 'absolute',
          inset: 0,
          radius: 'sm',
          background: { dark: '#1c2a4a', light: '#dbe5ff' },
        },
        {
          type: 'Box',
          position: 'absolute',
          top: 0,
          bottom: 0,
          left: 0,
          width: '62%',
          radius: 'sm',
          background: '#2f6df6',
        },
        {
          type: 'Box',
          position: 'absolute',
          inset: 0,
          align: 'center',
          justify: 'center',
          children: [
            { type: 'Text', value: '62%', weight: 'semibold', color: '#ffffff' },
          ],
        },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'ScrollRow',
      gap: 8,
      padding: { y: 4 },
      children: [
        { type: 'Badge', label: 'All', pill: true },
        { type: 'Badge', label: 'DeFi', pill: true, color: 'info' },
        { type: 'Badge', label: 'NFTs', pill: true, color: 'discovery' },
        { type: 'Badge', label: 'Governance', pill: true, color: 'success' },
        { type: 'Badge', label: 'Social', pill: true, color: 'warning' },
        { type: 'Badge', label: 'Gaming', pill: true, color: 'danger' },
        {
          type: 'Badge',
          label: 'Owner',
          pill: true,
          size: '3xs',
          weight: 'medium',
          background: { dark: 'rgba(45,212,191,0.18)', light: 'rgba(13,148,136,0.12)' },
          color: { dark: '#2dd4bf', light: '#0d9488' },
        },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'ColorPicker',
      name: 'demoColor',
      value: '#2f6df6',
      onChangeAction: { type: 'demo_color', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'ColorPicker',
      name: 'demoColorHsv',
      mode: 'hsv',
      value: '#2f6df6',
      onChangeAction: { type: 'demo_color', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Button',
      label: 'Custom color button',
      color: '#8b5cf6',
      onClickAction: { type: 'demo_button', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Pressable',
      onClickAction: { type: 'demo_press', handler: 'client' },
      onLongPressAction: { type: 'demo_longpress', handler: 'client' },
      onSwipeAction: { type: 'demo_swipe', handler: 'client' },
      children: [
        {
          type: 'Box',
          padding: { x: 12, y: 10 },
          radius: 'sm',
          background: { dark: '#1c1c1e', light: '#f0f0f2' },
          children: [{ type: 'Text', value: 'Tap, long-press, or swipe me' }],
        },
      ],
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'AudioPlayer',
      src: 'https://cdn.metro.box/sample.mp3',
      duration: 42,
      onPlayAction: { type: 'demo_audio', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'VideoPlayer',
      src: 'https://cdn.metro.box/sample.mp4',
      controls: true,
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'Button',
      label: 'Pick a file',
      onClickAction: { type: 'demo_pick', handler: 'client' },
    },
    {
      type: 'FilePicker',
      source: 'document',
      openNonce: 0,
      onPickAction: { type: 'demo_file', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'VoiceRecorder',
      recording: false,
      fg: { dark: '#ffffff', light: '#111114' },
      head: { dark: '#ffffff', light: '#111114' },
      sub: { dark: '#9a9a9f', light: '#71717a' },
      bg: { dark: '#0b0b0d', light: '#ffffff' },
      chipBg: { dark: '#1c1c1e', light: '#f0f0f2' },
      primary: { dark: '#2f6df6', light: '#2f6df6' },
      inputSlot: { type: 'Text', value: 'Press and hold the mic to record' },
      leftControls: { type: 'Icon', name: 'plus' },
      onStartAction: { type: 'demo_rec_start', handler: 'client' },
      onCancelAction: { type: 'demo_rec_cancel', handler: 'client' },
      onCompleteAction: { type: 'demo_rec_done', handler: 'client' },
    },
    { type: 'Spacer', minSize: 12 },
    {
      type: 'ListView',
      children: [
        {
          type: 'ListViewItem',
          padding: { x: 14, y: 14 },
          showDivider: true,
          border: { size: 1, color: { dark: '#00000000', light: '#00000000' } },
          pressedBorderColor: { dark: '#2f6df6', light: '#2f6df6' },
          onClickAction: { type: 'demo_list_item', handler: 'client' },
          children: [
            { type: 'Image', src: SAMPLE_IMAGE, size: 36, radius: 'full' },
            {
              type: 'Col',
              gap: 2,
              flex: 1,
              children: [
                { type: 'Text', value: 'Custom row', weight: 'semibold' },
                { type: 'Caption', value: 'padding 14, border-pressed, divider' },
              ],
            },
            { type: 'Icon', name: 'chevronRight' },
          ],
        },
        {
          type: 'ListViewItem',
          padding: { x: 14, y: 14 },
          onClickAction: { type: 'demo_list_item', handler: 'client' },
          children: [
            { type: 'Image', src: SAMPLE_IMAGE, size: 36, radius: 'full' },
            {
              type: 'Col',
              gap: 2,
              flex: 1,
              children: [
                { type: 'Text', value: 'Second row', weight: 'semibold' },
                { type: 'Caption', value: 'no divider on the last row' },
              ],
            },
            { type: 'Icon', name: 'chevronRight' },
          ],
        },
      ],
    },
  ],
};
