// Discord + Telegram station verb declarations (data only). Mirror the dispatch
// chains in stations/discord/actions.ts and stations/telegram/actions.ts.

import { v } from './schema.js';
import { line, type VerbDecl } from './registry-types.js';

const acct = v.optional(v.string());

export const DISCORD_VERBS: VerbDecl[] = [
  { name: 'accounts', owner: 'discord', kind: 'read', idempotent: true,
    description: 'List booted Discord accounts (id, userId, username, ready).',
    example: 'metro call discord accounts' },
  { name: 'send', owner: 'discord', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, text: v.optional(v.string()), account: acct }),
    description: 'Send a message to a channel.',
    example: 'metro send metro://discord/<chan> "hello"' },
  { name: 'reply', owner: 'discord', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, messageId: v.string(), text: v.string(), account: acct }),
    description: 'Reply to a message.',
    example: 'metro reply metro://discord/<chan> <msgId> "thanks"' },
  { name: 'react', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), emoji: v.optional(v.string()), account: acct }),
    description: 'Add (emoji) or remove (no emoji) a reaction.',
    example: 'metro react metro://discord/<chan> <msgId> 👍' },
  { name: 'edit', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), text: v.string(), account: acct }),
    description: 'Edit a previously-sent message.',
    example: 'metro edit metro://discord/<chan> <msgId> "fixed"' },
  { name: 'delete', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Delete a message.',
    example: 'metro delete metro://discord/<chan> <msgId>' },
  { name: 'fetch', owner: 'discord', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Fetch recent messages from a channel.',
    example: 'metro call discord fetch \'{"line":"…","limit":20}\'' },
  { name: 'download', owner: 'discord', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Download a message\'s attachments to disk.',
    example: 'metro call discord download \'{"line":"…","messageId":"…"}\'' },
  { name: 'thread_create', owner: 'discord', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, name: v.string(), account: acct }),
    description: 'Create a thread (from a message or standalone).',
    example: 'metro call discord thread_create \'{"line":"…","name":"…"}\'' },
  { name: 'pin', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Pin a message in a channel.',
    example: 'metro call discord pin \'{"line":"…","messageId":"…"}\'' },
  { name: 'typing', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a typing indicator to a channel.',
    example: 'metro call discord typing \'{"line":"…"}\'' },
  { name: 'channel', owner: 'discord', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Read channel metadata.',
    example: 'metro call discord channel \'{"line":"…"}\'' },
  { name: 'set_presence', owner: 'discord', kind: 'mutate', idempotent: true,
    description: 'Set the bot presence / custom status.',
    example: 'metro call discord set_presence \'{"status":"online"}\'' },
  { name: 'joinVoice', owner: 'discord', kind: 'mutate', idempotent: true,
    description: 'Join a voice channel.',
    example: 'metro call discord joinVoice \'{"line":"…"}\'' },
  { name: 'leaveVoice', owner: 'discord', kind: 'mutate', idempotent: true,
    description: 'Leave the current voice channel.',
    example: 'metro call discord leaveVoice \'{"line":"…"}\'' },
  { name: 'speak', owner: 'discord', kind: 'mutate', idempotent: false,
    description: 'Speak text (TTS) in a voice channel.',
    example: 'metro call discord speak \'{"line":"…","text":"…"}\'' },
  { name: 'voiceDebug', owner: 'discord', kind: 'read', idempotent: true,
    description: 'Dump voice-connection debug state.',
    example: 'metro call discord voiceDebug \'{"line":"…"}\'' },
  { name: 'voiceTranscribe', owner: 'discord', kind: 'mutate', idempotent: false,
    description: 'Transcribe captured voice audio.',
    example: 'metro call discord voiceTranscribe \'{"line":"…"}\'' },
];

export const TELEGRAM_VERBS: VerbDecl[] = [
  { name: 'accounts', owner: 'telegram', kind: 'read', idempotent: true,
    description: 'List booted Telegram accounts.',
    example: 'metro call telegram accounts' },
  { name: 'send', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, text: v.optional(v.string()), account: acct }),
    description: 'Send a text message to a chat.',
    example: 'metro send metro://telegram/<chat> "hello"' },
  { name: 'react', owner: 'telegram', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), emoji: v.optional(v.string()), account: acct }),
    description: 'Set (emoji) or clear (no emoji) a reaction on a message.',
    example: 'metro react metro://telegram/<chat> <msgId> 👍' },
  { name: 'edit', owner: 'telegram', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), text: v.string(), account: acct }),
    description: 'Edit a previously-sent message.',
    example: 'metro edit metro://telegram/<chat> <msgId> "fixed"' },
  { name: 'delete', owner: 'telegram', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Delete a message.',
    example: 'metro delete metro://telegram/<chat> <msgId>' },
  { name: 'send_photo', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a photo to a chat.',
    example: 'metro call telegram send_photo \'{"line":"…","path":"…"}\'' },
  { name: 'send_document', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a document/file to a chat.',
    example: 'metro call telegram send_document \'{"line":"…","path":"…"}\'' },
  { name: 'send_voice', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a voice note to a chat.',
    example: 'metro call telegram send_voice \'{"line":"…","path":"…"}\'' },
  { name: 'send_sticker', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a sticker to a chat.',
    example: 'metro call telegram send_sticker \'{"line":"…","sticker":"…"}\'' },
  { name: 'send_dice', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send an animated dice/emoji game to a chat.',
    example: 'metro call telegram send_dice \'{"line":"…"}\'' },
  { name: 'send_location', owner: 'telegram', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a location to a chat.',
    example: 'metro call telegram send_location \'{"line":"…","lat":0,"lon":0}\'' },
  { name: 'read', owner: 'telegram', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Read recent messages from a chat.',
    example: 'metro call telegram read \'{"line":"…"}\'' },
  { name: 'download', owner: 'telegram', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Download a message\'s media to disk.',
    example: 'metro call telegram download \'{"line":"…","messageId":"…"}\'' },
];
