// XMTP station verb declarations (data only). Mirrors the handlers in
// stations/xmtp/actions.ts (+ actions-conv / actions-push). The MUTATE entries
// here are a superset-consistent with the send-guard's GUARDED_XMTP_ACTIONS
// ({send, reply, react, sendAttachment, newDm, newGroup}); every one of those is
// kind:'mutate' below (asserted by test/registry.test.ts). The remaining mutates
// (ask, sendImage, tx/sig requests, channel-meta writes, closeGroup, push) also
// change remote state but are not identity-send-guarded today.

import { v } from './schema.js';
import { line, type VerbDecl } from './registry-types.js';

const acct = v.optional(v.string());

export const XMTP_VERBS: VerbDecl[] = [
  { name: 'accounts', owner: 'xmtp', kind: 'read', idempotent: true,
    description: 'List booted XMTP accounts (id, address, inboxId, owner).',
    example: 'metro call xmtp accounts' },
  { name: 'send', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, text: v.string(), account: acct }),
    description: 'Send a text message to a conversation.',
    example: 'metro send metro://xmtp/<acct>/<conv> "hello"' },
  { name: 'reply', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, replyTo: v.string(), text: v.string(), account: acct }),
    description: 'Reply to a specific message.',
    example: 'metro reply metro://xmtp/<acct>/<conv> <msgId> "thanks"' },
  { name: 'react', owner: 'xmtp', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), emoji: v.string(), account: acct }),
    description: 'Add (or remove) an emoji reaction to a message.',
    example: 'metro react metro://xmtp/<acct>/<conv> <msgId> 👍' },
  { name: 'sendAttachment', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a file/attachment (path or base64) to a conversation.',
    example: 'metro send metro://xmtp/<acct>/<conv> --attach ./pic.png' },
  { name: 'sendImage', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send an inline image to a conversation.',
    example: 'metro call xmtp sendImage \'{"line":"…","dataB64":"…"}\'' },
  { name: 'ask', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a poll / question (AskUserQuestion). Alias: sendPoll.',
    example: 'metro call xmtp ask \'{"line":"…","title":"…","choices":[…]}\'' },
  { name: 'sendPoll', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Alias of ask — send a poll.',
    example: 'metro call xmtp sendPoll \'{"line":"…","title":"…"}\'' },
  { name: 'sendTxRequest', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, to: v.string(), amountEth: v.number(), account: acct }),
    description: 'Send a wallet transaction request (payment) into a conversation.',
    example: 'metro call xmtp sendTxRequest \'{"line":"…","to":"0x…","amountEth":0.01}\'' },
  { name: 'sendSignatureRequest', owner: 'xmtp', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a signature request (eip712 or personal) into a conversation.',
    example: 'metro call xmtp sendSignatureRequest \'{"line":"…","kind":"personal"}\'' },
  { name: 'edit', owner: 'xmtp', kind: 'mutate', idempotent: true,
    description: 'Unsupported on XMTP (immutable log) — returns a uniform error.',
    example: 'metro edit metro://xmtp/<acct>/<conv> <msgId> "…"' },
  { name: 'delete', owner: 'xmtp', kind: 'mutate', idempotent: true,
    description: 'Unsupported on XMTP (immutable log) — returns a uniform error.',
    example: 'metro delete metro://xmtp/<acct>/<conv> <msgId>' },
  { name: 'newDm', owner: 'xmtp', kind: 'mutate', idempotent: false,
    description: 'Create a new direct-message conversation with a peer.',
    example: 'metro call xmtp newDm \'{"address":"0x…"}\'' },
  { name: 'newGroup', owner: 'xmtp', kind: 'mutate', idempotent: false,
    description: 'Create a new group conversation.',
    example: 'metro call xmtp newGroup \'{"members":["0x…"]}\'' },
  { name: 'createRequestGroup', owner: 'xmtp', kind: 'mutate', idempotent: false,
    description: 'Create a request (pending) group conversation.',
    example: 'metro call xmtp createRequestGroup \'{…}\'' },
  { name: 'setLabels', owner: 'xmtp', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line }),
    description: 'Set the labels on a conversation (channel metadata).',
    example: 'metro call xmtp setLabels \'{"line":"…","labels":["bug"]}\'' },
  { name: 'setGithub', owner: 'xmtp', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line }),
    description: 'Attach a GitHub link to a conversation (channel metadata).',
    example: 'metro call xmtp setGithub \'{"line":"…","url":"…"}\'' },
  { name: 'setPreview', owner: 'xmtp', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line }),
    description: 'Attach a preview deep-link to a conversation (channel metadata).',
    example: 'metro call xmtp setPreview \'{"line":"…","url":"…"}\'' },
  { name: 'updateChannelMeta', owner: 'xmtp', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line }),
    description: 'Update arbitrary channel metadata fields.',
    example: 'metro call xmtp updateChannelMeta \'{"line":"…","name":"…"}\'' },
  { name: 'closeGroup', owner: 'xmtp', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line }),
    description: 'Close / archive a group conversation.',
    example: 'metro call xmtp closeGroup \'{"line":"…"}\'' },
  { name: 'query', owner: 'xmtp', kind: 'read', idempotent: true,
    description: 'Query conversation/member info.',
    example: 'metro call xmtp query \'{"line":"…"}\'' },
  { name: 'groupInfo', owner: 'xmtp', kind: 'read', idempotent: true,
    inputSchema: v.object({ line }),
    description: 'Read group info (members, addresses) for a conversation.',
    example: 'metro call xmtp groupInfo \'{"line":"…"}\'' },
  { name: 'listConvs', owner: 'xmtp', kind: 'read', idempotent: true,
    description: 'List known conversations for the account.',
    example: 'metro call xmtp listConvs' },
  { name: 'register-push', owner: 'xmtp', kind: 'mutate', idempotent: true,
    description: 'Register an FCM push token for an account.',
    example: 'metro call xmtp register-push \'{"token":"…"}\'' },
  { name: 'list-push', owner: 'xmtp', kind: 'read', idempotent: true,
    description: 'List registered push tokens.',
    example: 'metro call xmtp list-push' },
  { name: 'test-push', owner: 'xmtp', kind: 'mutate', idempotent: false,
    description: 'Send a test push notification.',
    example: 'metro call xmtp test-push \'{"title":"hi"}\'' },
  { name: 'unregister-push', owner: 'xmtp', kind: 'mutate', idempotent: true,
    description: 'Remove a registered push token.',
    example: 'metro call xmtp unregister-push \'{"token":"…"}\'' },
  { name: 'disable-push', owner: 'xmtp', kind: 'mutate', idempotent: true,
    description: 'Disable push delivery for an account/token.',
    example: 'metro call xmtp disable-push \'{…}\'' },
];
