apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'box.stage.speech'
version = '0.1.0'

android {
  namespace 'box.stage.speech'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  testOptions {
    unitTests.all {
      testLogging.events 'passed', 'skipped', 'failed'
    }
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
